"""add message column to connection requests

Revision ID: a453dec4eda7
Revises: 92f591df6fd7
Create Date: 2026-03-26 18:35:21.931668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a453dec4eda7'
down_revision: Union[str, Sequence[str], None] = '92f591df6fd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connection_requests', sa.Column('message', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('connection_requests', 'message')
    # ### end Alembic commands ###
